hautelook_alice:
    root_dirs:
        - fixtures
    fixtures_path:
        - Player
        - User
        - Game
        - LobbyConfiguration
        - Lobby
        - Set
        - MatchResolution
        - Match
